[package]
name = "hypervolume"
version = "0.1.0"
authors = ["hvy <hiroyuki.vincent.yamazaki@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
regex = "1"